import Head from "next/head"
import React, { useEffect, useState } from "react"

import Login from "components/Login"
import { Layout } from "components/Layout"
import { ChatActivo } from "components/WindowRight/ChatActivo"
import { ChatInactivo } from "components/WindowRight/ChatInactivo"
import { PreviewBackground } from "components/WindowRight/PreviewBackground"
import { useSidebar } from "context/SidebarContext"
import { NextPage } from "next/types"
import { userCookie } from "utils/userCookie"

const Inicio: NextPage = () => {
  const { windowRight } = useSidebar()

  const [loading, setLoading] = useState(true)
  const logged = userCookie()

  useEffect(() => {
    setLoading(false)
  }, [])

  return (
    <>
      <Head>
        <title>Whatsapp Clone</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <>
        {!loading && (
          <>
            {!logged ? (
              <Login />
            ) : (
              <Layout>
                {windowRight === "ChatInactivo" ? (
                  <ChatInactivo />
                ) : windowRight === "ChatActivo" ? (
                  <ChatActivo />
                ) : windowRight === "PreviewBackground" ? (
                  <PreviewBackground />
                ) : null}
              </Layout>
            )}
          </>
        )}
      </>
    </>
  )
}

export default Inicio
