import Head from 'next/head'
import Image from "next/image"
import { useEffect } from "react"
import { } from "animate.css"

import { ChatInactivo } from '../components/Chat'
import { NavUser } from '../components/NavUser'
import { ListaChat } from '../components/ListaChats'


export default function Home() {

  useEffect(() => {
    const preload = document.getElementById("preload")
    const home = document.getElementById("home")

    setTimeout(() => {
      preload.classList.add("inactivo")
      home.classList.add("activo")
    }, 4000);

  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div id="preload" className="preload">
        <div className="flex flex-col justify-center items-center mx-auto w-2/6 text-center">
          <div>
            <Image src="/whatsapp.svg" width={50} height={50} className="animate__animated animate__flash animate__slower animate__infinite" />
          </div>
          <div className="barra"></div>
          <div>
            <h1 className="text-white text-lg">WhatsApp</h1>
            <p className="text-gray-600">Cifrado de extremo a extremo</p>
          </div>
        </div>
      </div>

      <div id="home" className="home activo">
        <div style={{ width: "1280px", height: "700px" }}>
          <div className="flex flex-row h-full">
            <div className="flex flex-col w-2/6 border-r border-gray-600">
              <NavUser />
              <ListaChat />
            </div>
            <div className="flex flex-row w-4/6 h-full">
              <ChatInactivo />
            </div>
          </div>
        </div>
      </div>

    </>
  )
}
